"""
Local HTTPS API for masking-as-a-service.

Design constraints:
  * Bound to 127.0.0.1 only — never to 0.0.0.0. External access is a non-goal.
  * Self-signed TLS cert auto-generated under the user data dir.
  * Bearer-token auth (`Authorization: Bearer <token>`) — token autogenerated
    on first run, stored at api_token_path() with restrictive perms.
  * Constant-time token comparison (hmac.compare_digest).
  * Per-token in-memory rate limit (default 60 req / minute).
  * Body size hard cap (default 25 MiB) to prevent memory pressure.

Endpoints (all prefixed /v1):
  GET  /v1/health                 — auth-free liveness probe
  POST /v1/mask                   — JSON: {"text": "..."} → {"masked": "..."}
  POST /v1/unmask                 — JSON: {"text": "..."} → {"unmasked": "..."}
  POST /v1/mask/file              — multipart: file=@x.docx, ext=.docx
  POST /v1/unmask/file            — multipart: file=@x.docx, ext=.docx
  POST /v1/detect                 — JSON: {"text": "..."} → {"candidates": [...]}
  GET  /v1/dictionary             — list dictionary entries
  POST /v1/dictionary             — JSON: {"term": "..."} → {"id":..,"token":..}
  DELETE /v1/dictionary/<id>      — remove entry by id
  GET  /v1/patterns               — list user patterns
  POST /v1/patterns               — JSON: {"name":"..","regex":".."}
  DELETE /v1/patterns/<id>        — remove pattern by id
"""
from __future__ import annotations

import hmac
import io
import time
from collections import deque
from functools import wraps
from pathlib import Path
from threading import RLock
from typing import Callable

from flask import Flask, jsonify, request, Response, send_file

from doc_sanitizer import crypto, paths
from doc_sanitizer.sanitizer import Sanitizer

DEFAULT_HOST = "127.0.0.1"
DEFAULT_PORT = 8443
MAX_BODY_BYTES = 25 * 1024 * 1024
RATE_LIMIT_PER_MIN = 60


# ── auth + rate-limit decorators ───────────────────────────────────────────

class _RateLimiter:
    def __init__(self, per_minute: int = RATE_LIMIT_PER_MIN) -> None:
        self.per_minute = per_minute
        self._lock = RLock()
        self._hits: dict[str, deque[float]] = {}

    def allow(self, key: str) -> bool:
        now = time.monotonic()
        with self._lock:
            dq = self._hits.setdefault(key, deque())
            while dq and now - dq[0] > 60.0:
                dq.popleft()
            if len(dq) >= self.per_minute:
                return False
            dq.append(now)
            return True


def _require_auth(expected_token: str, limiter: _RateLimiter) -> Callable:
    def deco(fn: Callable) -> Callable:
        @wraps(fn)
        def wrapper(*args, **kwargs):
            header = request.headers.get("Authorization", "")
            if not header.startswith("Bearer "):
                return _err(401, "missing bearer token")
            presented = header[7:].strip()
            if not hmac.compare_digest(presented, expected_token):
                return _err(401, "invalid bearer token")
            client_id = presented[:8]  # token-prefix is enough for per-token bucketing
            if not limiter.allow(client_id):
                return _err(429, "rate limit exceeded")
            return fn(*args, **kwargs)
        return wrapper
    return deco


def _err(status: int, msg: str) -> Response:
    resp = jsonify({"error": msg})
    resp.status_code = status
    return resp


# ── factory ─────────────────────────────────────────────────────────────────

def create_app(sanitizer: Sanitizer | None = None,
               token: str | None = None) -> Flask:
    app = Flask("doc_sanitizer.api")
    app.config["MAX_CONTENT_LENGTH"] = MAX_BODY_BYTES

    sanitizer = sanitizer or Sanitizer()
    expected_token = token or crypto.get_or_create_api_token()
    limiter = _RateLimiter()
    require = _require_auth(expected_token, limiter)

    @app.errorhandler(413)
    def _too_big(_):
        return _err(413, f"body exceeds {MAX_BODY_BYTES} bytes")

    @app.errorhandler(404)
    def _nf(_):
        return _err(404, "not found")

    @app.errorhandler(405)
    def _na(_):
        return _err(405, "method not allowed")

    @app.errorhandler(Exception)
    def _ex(e):
        # Never leak stack traces / paths — opaque error.
        app.logger.exception("unhandled API error")
        return _err(500, "internal error")

    @app.after_request
    def _harden(resp: Response) -> Response:
        resp.headers["X-Content-Type-Options"] = "nosniff"
        resp.headers["Referrer-Policy"] = "no-referrer"
        resp.headers["Cache-Control"] = "no-store"
        resp.headers["Strict-Transport-Security"] = "max-age=63072000"
        resp.headers["X-Frame-Options"] = "DENY"
        return resp

    # ── health ──────────────────────────────────────────────────────────────
    @app.get("/v1/health")
    def health():
        return jsonify({"status": "ok", "version": _version()})

    # ── text mask/unmask ────────────────────────────────────────────────────
    @app.post("/v1/mask")
    @require
    def mask_text():
        body = request.get_json(silent=True) or {}
        text = body.get("text")
        if not isinstance(text, str):
            return _err(400, "field 'text' (string) required")
        auto_add = bool(body.get("auto_add", False))
        return jsonify({"masked": sanitizer.mask_text(text, auto_add=auto_add)})

    @app.post("/v1/unmask")
    @require
    def unmask_text():
        body = request.get_json(silent=True) or {}
        text = body.get("text")
        if not isinstance(text, str):
            return _err(400, "field 'text' (string) required")
        return jsonify({"unmasked": sanitizer.unmask_text(text)})

    @app.post("/v1/detect")
    @require
    def detect():
        body = request.get_json(silent=True) or {}
        text = body.get("text")
        if not isinstance(text, str):
            return _err(400, "field 'text' (string) required")
        return jsonify({"candidates": sanitizer.detect(text)})

    # ── file mask/unmask ────────────────────────────────────────────────────
    @app.post("/v1/mask/file")
    @require
    def mask_file():
        f = request.files.get("file")
        if not f or not f.filename:
            return _err(400, "multipart field 'file' required")
        ext = (request.form.get("ext") or Path(f.filename).suffix).lower()
        if not ext:
            return _err(400, "could not infer extension; pass form field 'ext'")
        auto_add = request.form.get("auto_add", "").lower() in {"1", "true", "yes"}
        try:
            out = sanitizer.mask_file(f.read(), ext, auto_add=auto_add)
        except ValueError as e:
            return _err(400, str(e))
        return _send_bytes(out, ext, prefix="masked_")

    @app.post("/v1/unmask/file")
    @require
    def unmask_file():
        f = request.files.get("file")
        if not f or not f.filename:
            return _err(400, "multipart field 'file' required")
        ext = (request.form.get("ext") or Path(f.filename).suffix).lower()
        if not ext:
            return _err(400, "could not infer extension; pass form field 'ext'")
        try:
            out = sanitizer.unmask_file(f.read(), ext)
        except ValueError as e:
            return _err(400, str(e))
        return _send_bytes(out, ext, prefix="unmasked_")

    # ── dictionary ──────────────────────────────────────────────────────────
    @app.get("/v1/dictionary")
    @require
    def list_dict():
        return jsonify({"entries": sanitizer.dictionary()})

    @app.post("/v1/dictionary")
    @require
    def add_dict():
        body = request.get_json(silent=True) or {}
        term = (body.get("term") or "").strip()
        if not term:
            return _err(400, "field 'term' required")
        return jsonify(sanitizer.add_term(term, token=body.get("token")))

    @app.delete("/v1/dictionary/<int:eid>")
    @require
    def del_dict(eid: int):
        sanitizer.remove_term(eid)
        return ("", 204)

    # ── patterns ────────────────────────────────────────────────────────────
    @app.get("/v1/patterns")
    @require
    def list_patterns():
        return jsonify({"patterns": sanitizer.patterns()})

    @app.post("/v1/patterns")
    @require
    def add_pattern_route():
        body = request.get_json(silent=True) or {}
        name = (body.get("name") or "").strip()
        regex = (body.get("regex") or "").strip()
        if not name or not regex:
            return _err(400, "fields 'name' and 'regex' required")
        try:
            sanitizer.add_pattern(name, regex)
        except Exception as e:
            return _err(400, f"invalid regex: {e}")
        return ("", 201)

    @app.delete("/v1/patterns/<int:pid>")
    @require
    def del_pattern(pid: int):
        sanitizer.remove_pattern(pid)
        return ("", 204)

    return app


# ── helpers ─────────────────────────────────────────────────────────────────

def _send_bytes(data: bytes, ext: str, prefix: str = "") -> Response:
    mime_map = {
        ".docx": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        ".pptx": "application/vnd.openxmlformats-officedocument.presentationml.presentation",
        ".xlsx": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    }
    return send_file(
        io.BytesIO(data),
        mimetype=mime_map.get(ext, "application/octet-stream"),
        as_attachment=True,
        download_name=f"{prefix}output{ext}",
    )


def _version() -> str:
    from doc_sanitizer import __version__
    return __version__


# ── server entrypoint ──────────────────────────────────────────────────────

def serve(host: str = DEFAULT_HOST, port: int = DEFAULT_PORT,
          quiet: bool = False) -> None:
    """Block, serving HTTPS on host:port. Auto-creates cert/token on first run."""
    if host not in ("127.0.0.1", "::1", "localhost"):
        raise ValueError(
            f"refusing to bind to non-loopback host {host!r}; "
            "this API is local-only by design"
        )
    cert, key = crypto.get_or_create_tls_cert()
    token = crypto.get_or_create_api_token()
    app = create_app(token=token)

    if not quiet:
        print(f"[doc-sanitizer] HTTPS API listening on https://{host}:{port}")
        print(f"[doc-sanitizer] data dir : {paths.user_data_dir()}")
        print(f"[doc-sanitizer] cert     : {cert}")
        print(f"[doc-sanitizer] token    : {paths.api_token_path()} (chmod 600)")
        print(f"[doc-sanitizer] auth     : Authorization: Bearer {token}")

    # Use the cheroot/Werkzeug dev server with TLS — fine for local-only use.
    app.run(host=host, port=port, ssl_context=(str(cert), str(key)),
            debug=False, threaded=True)
